In [4]:
%pip install pip==23.2

  Using cached pip-23.2-py3-none-any.whl.metadata (4.2 kB)
Using cached pip-23.2-py3-none-any.whl (2.1 MB)
  Attempting uninstall: pip
    Found existing installation: pip 24.3.1
    Uninstalling pip-24.3.1:
      Successfully uninstalled pip-24.3.1
Note: you may need to restart the kernel to use updated packages.


In [5]:
%pip install gym-retro


[notice] A new release of pip is available: 23.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [6]:
%pip install setuptools==65.5.0 "wheel<0.40.0"

  Obtaining dependency information for setuptools==65.5.0 from https://files.pythonhosted.org/packages/41/82/7f54bbfe5c247a8c9f78d8d1d7c051847bcb78843c397b866dba335c1e88/setuptools-65.5.0-py3-none-any.whl.metadata
  Using cached setuptools-65.5.0-py3-none-any.whl.metadata (6.3 kB)
  Obtaining dependency information for wheel<0.40.0 from https://files.pythonhosted.org/packages/bd/7c/d38a0b30ce22fc26ed7dbc087c6d00851fb3395e9d0dac40bec1f905030c/wheel-0.38.4-py3-none-any.whl.metadata
  Using cached wheel-0.38.4-py3-none-any.whl.metadata (2.1 kB)
Using cached setuptools-65.5.0-py3-none-any.whl (1.2 MB)
Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
  Attempting uninstall: setuptools
    Found existing installation: setuptools 49.2.1
    Uninstalling setuptools-49.2.1:
      Successfully uninstalled setuptools-49.2.1

[notice] A new release of pip is available: 23.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packag

In [7]:
%pip install gym==0.21.0

  Using cached gym-0.21.0-py3-none-any.whl
  Attempting uninstall: gym
    Found existing installation: gym 0.26.2
    Uninstalling gym-0.26.2:
      Successfully uninstalled gym-0.26.2

[notice] A new release of pip is available: 23.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [8]:
%pip install opencv-python

  Obtaining dependency information for opencv-python from https://files.pythonhosted.org/packages/64/4a/016cda9ad7cf18c58ba074628a4eaae8aa55f3fd06a266398cef8831a5b9/opencv_python-4.10.0.84-cp37-abi3-macosx_12_0_x86_64.whl.metadata
  Using cached opencv_python-4.10.0.84-cp37-abi3-macosx_12_0_x86_64.whl.metadata (20 kB)
Using cached opencv_python-4.10.0.84-cp37-abi3-macosx_12_0_x86_64.whl (56.5 MB)

[notice] A new release of pip is available: 23.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [9]:
%pip install gym gym-retro


[notice] A new release of pip is available: 23.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [22]:
%pip install matplotlib

  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/b1/ea/129163dcd21db6da5d559a8160c4a74c1dc5f96ac246a3d4248b43c7648d/matplotlib-3.7.5-cp38-cp38-macosx_10_12_x86_64.whl.metadata
  Using cached matplotlib-3.7.5-cp38-cp38-macosx_10_12_x86_64.whl.metadata (5.7 kB)
  Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/02/7e/ffaba1bf3719088be3ad6983a5e85e1fc9edccd7b406b98e433436ecef74/contourpy-1.1.1-cp38-cp38-macosx_10_9_x86_64.whl.metadata
  Using cached contourpy-1.1.1-cp38-cp38-macosx_10_9_x86_64.whl.metadata (5.9 kB)
  Obtaining dependency information for cycler>=0.10 from https://files.pythonhosted.org/packages/e7/05/c19819d5e3d95294a6f5947fb9b9629efb316b96de511b418c53d245aae6/cycler-0.12.1-py3-none-any.whl.metadata
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Obtaining dependency information for fonttools>=4.22.0 from https://files.pythonhosted.org/packages/3f/b2/92fbceab8e

### Take note of my versions^

In [10]:
# Import retro to play Street Fighter using a ROM
import retro
# Import time to slow down game
import time

In [15]:
# %%python -m retro.import . # Run this from the roms folder, or where you have your game roms 

UsageError: %%python is a cell magic, but the cell body is empty.


In [23]:
# Import environment base class for a wrapper 
from gym import Env 
# Import the space shapes for the environment
from gym.spaces import MultiBinary, Box
# Import numpy to calculate frame delta 
import numpy as np
# Import opencv for grayscaling
import cv2
# Import matplotlib for plotting the image
from matplotlib import pyplot as plt

In [24]:
# Create custom environment 
class StreetFighter(Env): # pass in basic env from above to preprocessing
    def __init__(self):
        super().__init__() # inherit from base env
        # Specify action space and observation space 
        self.observation_space = Box(low=0, high=255, shape=(84, 84, 1), dtype=np.uint8) # grayscaled frame, smaller amt of pixels
        self.action_space = MultiBinary(12) # type of actions that can be taken
        self.health = 144
        self.enemy_health = 144
        self.score = 0
        self.matches_won = 0
        self.continue_timer = 100
        self.enemy_matches_won = 0
        self.previous_action = np.zeros(12)
        # Startup and instance of the game 
        self.game = retro.make(game='StreetFighterIISpecialChampionEdition-Genesis', use_restricted_actions=retro.Actions.FILTERED) # used to get valid button combos
    
    def reset(self): # restart
        # Return the first frame 
        obs = self.game.reset()
        obs = self.preprocess(obs) 
        self.previous_frame = obs # sets previous frame to current frame
        
        # Create a attribute to hold the score delta 
        self.score = 0 
        return obs
    
    def preprocess(self, observation): # grayscale, resize
        # Grayscaling 
        gray = cv2.cvtColor(observation, cv2.COLOR_BGR2GRAY)
        # Resize 
        resize = cv2.resize(gray, (84,84), interpolation=cv2.INTER_CUBIC)
        # Add the channels value
        channels = np.reshape(resize, (84,84,1))
        return channels 
    
    def reward_function(self, state, action):
        # Extract variables
        continuetimer = state['continuetimer']
        enemy_matches_won = state['enemy_matches_won']
        enemy_health = state['enemy_health']
        health = state['health']
        matches_won = state['matches_won']
        score = state['score']

        # Initialize reward
        reward = 0

        # Reward for increasing score each frame (scaled down to avoid excessively large rewards)
        reward += score * 0.001  

        # Reward for inflicting damage on the enemy, only if enemy_health is reduced
        if enemy_health < self.enemy_health:
            reward += (self.enemy_health - enemy_health) * 10

        # Penalty for losing health (scaled so health loss gives a clear penalty)
        if health < self.health:
            reward -= (self.health - health) * 10

        # Bonus if the player maintains health
        reward += health * 0.05  

        # Encourage the AI to win matches
        if matches_won > self.matches_won:
            reward += 200  # Winning a match should give a significant reward

        # Penalize the AI if the enemy wins a match
        if enemy_matches_won > self.enemy_matches_won:
            reward -= 200

        # Small positive reward to encourage efficient play (keeping the timer active)
        reward += continuetimer * 0.01  

        # Penalize the AI for taking actions that do not lead to damage dealt
        if enemy_health == self.enemy_health and action != np.zeros(12):
            reward -= 1


        # Update previous states to enable frame-by-frame comparison
        self.enemy_health = enemy_health
        self.health = health
        self.matches_won = matches_won
        self.enemy_matches_won = enemy_matches_won
        self.continue_timer = continuetimer
        self.score = score

        return reward
    
    def step(self, action): # how do we process action
        # Take a step 
        obs, reward, done, info = self.game.step(action)
        obs = self.preprocess(obs) 

        self.previous_action = action
        
        # Frame delta 
        frame_delta = obs - self.previous_frame # change in pixels (was dropped in final model of tutorial)
        self.previous_frame = obs 
        
        # Reshape the reward function
        reward = self.reward_function(info, action)

        return frame_delta, reward, done, info
    
    def render(self, *args, **kwargs): # unpack any args and kwargs from stable baseline
        self.game.render()
        
    def close(self):
        self.game.close()

In [25]:
env = StreetFighter()

In [27]:
# Reset game to starting state
obs = env.reset()
# Set flag to flase
done = False
for game in range(1): 
    while not done: 
        if done: 
            obs = env.reset()
        env.render()
        obs, reward, done, info = env.step(env.action_space.sample())
        time.sleep(0.01)
        if reward != 0:
            print(reward)

7.800000000000001
8.3
8.100000000000001
8.100000000000001
8.4
8.200000000000001
8.100000000000001
8.200000000000001
8.3
8.600000000000001
8.5
8.3
8.3
8.200000000000001
8.600000000000001
8.3
8.200000000000001
8.3
8.5
8.4
8.4
8.200000000000001
8.200000000000001
8.5
8.3
8.200000000000001
8.5
8.100000000000001
8.3
7.9
8.200000000000001
8.3
8.600000000000001
8.200000000000001
8.200000000000001
8.3
8.0
8.4
8.0
8.3
8.200000000000001
8.600000000000001
7.9
7.9
7.9
8.4
8.200000000000001
8.200000000000001
8.200000000000001
8.4
8.100000000000001
7.9
8.3
7.9
8.3
8.100000000000001
8.200000000000001
8.5
8.200000000000001
8.3
8.3
8.200000000000001
8.200000000000001
8.3
8.100000000000001
8.0
8.200000000000001
8.100000000000001
8.200000000000001
8.4
8.200000000000001
8.3
8.100000000000001
8.100000000000001
8.100000000000001
8.4
8.100000000000001
8.100000000000001
8.200000000000001
8.0
8.3
8.200000000000001
8.5
8.200000000000001
8.200000000000001
7.9
8.3
7.800000000000001
8.4
8.200000000000001
8.4
7.9
8.

In [26]:
# Closes the game environment - important given we can only run one at a time 
env.close()

# Hyperparameter Tune

https://pytorch.org/get-started/locally/  <- use this site to download pytorch

In [28]:
%pip install torch torchvision torchaudio

  Obtaining dependency information for torch from https://files.pythonhosted.org/packages/35/70/a14c72d280483b86939adf22c780bc81728dde26e89bc7aeb3d2ba63b063/torch-2.2.2-cp38-none-macosx_10_9_x86_64.whl.metadata
  Using cached torch-2.2.2-cp38-none-macosx_10_9_x86_64.whl.metadata (25 kB)
  Obtaining dependency information for torchvision from https://files.pythonhosted.org/packages/94/ce/b2ee0129bfe1280ae23e6f45d918072945676b14e80af750d7b3d63eecea/torchvision-0.17.2-cp38-cp38-macosx_10_13_x86_64.whl.metadata
  Using cached torchvision-0.17.2-cp38-cp38-macosx_10_13_x86_64.whl.metadata (6.6 kB)
  Obtaining dependency information for torchaudio from https://files.pythonhosted.org/packages/ff/b6/87316feb58466fe9683f91a3221f7b024e707c2365be23bd60c626067c4c/torchaudio-2.2.2-cp38-cp38-macosx_10_13_x86_64.whl.metadata
  Using cached torchaudio-2.2.2-cp38-cp38-macosx_10_13_x86_64.whl.metadata (6.4 kB)
  Obtaining dependency information for filelock from https://files.pythonhosted.org/packages/b9

In [30]:
%pip install 'stable-baselines3[extra]==1.3.0'

  Obtaining dependency information for stable-baselines3[extra]==1.3.0 from https://files.pythonhosted.org/packages/ea/c1/bdf01c4753ca3b4a99248a179446c5f42109f4485c606fd7e96e7090d4b9/stable_baselines3-1.3.0-py3-none-any.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 26.8 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/78/a8/07dd10f90ca915ed914853cd57f79bfc22e1ef4384ab56cb4336d2fc1f2a/pandas-2.0.3-cp38-cp38-macosx_10_9_x86_64.whl.metadata
  Using cached pandas-2.0.3-cp38-cp38-macosx_10_9_x86_64.whl.metadata (18 kB)
  Obtaining dependency information for atari-py~=0.2.0 from https://files.pythonhosted.org/packages/ad/4c/30800b0a5366abb58df3c85057a878818d86156051fc2c26540639eb13c3/atari_py-0.2.9-cp38-cp38-macosx_10_12_x86_64.whl.metadata
  Obtaining dependency information for tensorboard>=2.2.0 from https://files.pythonhosted.org/packages/bc/a2/ff5f4c299eb37

above is mac specific, remove quotes and run if not using zsh

In [31]:
%pip install optuna

  Obtaining dependency information for optuna from https://files.pythonhosted.org/packages/4e/41/2a2f5ed6c997367ab7055185cf66d536c228b15a12b8e112a274808f48b5/optuna-4.0.0-py3-none-any.whl.metadata
  Using cached optuna-4.0.0-py3-none-any.whl.metadata (16 kB)
  Obtaining dependency information for alembic>=1.5.0 from https://files.pythonhosted.org/packages/cb/06/8b505aea3d77021b18dcbd8133aa1418f1a1e37e432a465b14c46b2c0eaa/alembic-1.14.0-py3-none-any.whl.metadata
  Obtaining dependency information for colorlog from https://files.pythonhosted.org/packages/e3/51/9b208e85196941db2f0654ad0357ca6388ab3ed67efdbfc799f35d1f83aa/colorlog-6.9.0-py3-none-any.whl.metadata
  Using cached colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
  Obtaining dependency information for sqlalchemy>=1.3.0 from https://files.pythonhosted.org/packages/db/da/443679a0b9e0a009f00d1542595c8a4d582ece1809704e703c4843f18768/SQLAlchemy-2.0.36-cp38-cp38-macosx_10_9_x86_64.whl.metadata
  Using cached SQLAlchemy-2.0.36-cp38-cp

In [32]:
# Importing the optimzation frame - HPO
import optuna
# PPO algo for RL
from stable_baselines3 import PPO
# Bring in the eval policy method for metric calculation
from stable_baselines3.common.evaluation import evaluate_policy
# Import the sb3 monitor for logging 
from stable_baselines3.common.monitor import Monitor
# Import the vec wrappers to vectorize and frame stack
from stable_baselines3.common.vec_env import DummyVecEnv, VecFrameStack
# Import os to deal with filepaths
import os

/Users/suyogkhanal/Coding Projects/StreetFighterAI/.venv/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [64]:
LOG_DIR = './logs/'
OPT_DIR = './opt/'

In [62]:
# Function to return test hyperparameters - define the object function
def optimize_ppo(trial): 
    return {
        'n_steps':trial.suggest_int('n_steps', 2048, 8192), # number of frames used in one batch of training (must use a factor of 64) (maybe take a number and multiply it by 64? 😎🤝😈)
        'gamma':trial.suggest_loguniform('gamma', 0.8, 0.9999), # discount rate
        'learning_rate':trial.suggest_loguniform('learning_rate', 1e-5, 1e-4), # how fast we tune optimizer (Critic and Actor for PPO)
        'clip_range':trial.suggest_uniform('clip_range', 0.1, 0.4), # how far we want to clip for our advantage value in PPO
        'gae_lambda':trial.suggest_uniform('gae_lambda', 0.8, 0.99) # smoothing parameter (used when calculating advantage)
    }

# IF U WANT TO USE OTHER ALGOS THE HYPERPARAMS MUST BE SWITCHED AS WELL (DQN, SAC, etc.)

In [145]:
# alternative version to use later to bypass factor 64 error



# # PPO optimization parameters

# PPO_PARAMS = {

#     'n_steps_range': (2048, 8192),

#     'gamma_range': (0.8, 0.9999),

#     'learning_rate_range': (1e-5, 1e-4),

#     'clip_range_range': (0.1, 0.4),

#     'gae_lambda_range': (0.8, 0.99),

# }

# # Define the optimization function for PPO

# def optimize_ppo(trial): 

#     n_steps = trial.suggest_categorical('n_steps', range(PPO_PARAMS['n_steps_range'][0], PPO_PARAMS['n_steps_range'][1], 64))  # Steps of 64

#     return {

#         'n_steps': n_steps,

#         'gamma': trial.suggest_loguniform('gamma', *PPO_PARAMS['gamma_range']),

#         'learning_rate': trial.suggest_loguniform('learning_rate', *PPO_PARAMS['learning_rate_range']),

#         'clip_range': trial.suggest_uniform('clip_range', *PPO_PARAMS['clip_range_range']),

#         'gae_lambda': trial.suggest_uniform('gae_lambda', *PPO_PARAMS['gae_lambda_range']),

#     }

In [66]:
SAVE_PATH = os.path.join(OPT_DIR, 'trial_{}_best_model'.format(1))

In [65]:
# Run a training loop and return mean reward 
def optimize_agent(trial):
    # try:
        model_params = optimize_ppo(trial)  # get dict of hyperparams

        # Create environment 
        env = StreetFighter()
        env = Monitor(env, LOG_DIR) # allowd for logging mean episode reward and mean episode length
        env = DummyVecEnv([lambda: env])
        env = VecFrameStack(env, 4, channels_order='last')

        # Create algo 
        model = PPO('CnnPolicy', env, tensorboard_log=LOG_DIR, verbose=0, **model_params) # uses model params dict
        model.learn(total_timesteps=10000) # 100000 for production model (longer if can)

        # Evaluate model 
        mean_reward, _ = evaluate_policy(model, env, n_eval_episodes=1) # 5 different games usually but went lower cuz i dont got cuda (those who know)
        env.close()

        SAVE_PATH = os.path.join(OPT_DIR, 'trial_{}_best_model'.format(trial.number))
        model.save(SAVE_PATH)

        return mean_reward

    # except Exception as e: # used in case hyperparam throws error (allows to continue training)
    #     return -1000

In [69]:
# Creating the experiment 
study = optuna.create_study(direction='maximize') # since mean reward is positive we maximize, otherwise minimize
study.optimize(optimize_agent, n_trials=1, n_jobs=1) # for prod used n_trials=100

[I 2024-11-04 00:21:22,524] A new study created in memory with name: no-name-75b592f5-3a58-44ac-9aec-20831c7c628e
/var/folders/d4/_v_lx6gx66z8htqrwxr89lvc0000gn/T/ipykernel_86005/3706438210.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'gamma':trial.suggest_loguniform('gamma', 0.8, 0.9999), # discount rate
/var/folders/d4/_v_lx6gx66z8htqrwxr89lvc0000gn/T/ipykernel_86005/3706438210.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate':trial.suggest_loguniform('learning_rate', 1e-5, 1e-4), # how fast we tune optimizer (Critic and Actor for PPO)
/var/folders/d4/_v_lx6gx66z8htqrwxr89lvc0000gn/T/ipykernel_86005/3706438210.py:7: FutureWarning: suggest_unif

RuntimeError: Cannot create multiple emulator instances per process, make sure to call env.close() on each environment before creating a new one

In [74]:
study.best_params

{'n_steps': 7717,
 'gamma': 0.8951474854534238,
 'learning_rate': 1.5173785862671653e-05,
 'clip_range': 0.13355095227019517,
 'gae_lambda': 0.9181855173148512}

In [75]:
study.best_trial

FrozenTrial(number=0, state=TrialState.COMPLETE, values=[2000.0], datetime_start=datetime.datetime(2024, 10, 22, 1, 12, 54, 242354), datetime_complete=datetime.datetime(2024, 10, 22, 1, 14, 56, 805445), params={'n_steps': 7717, 'gamma': 0.8951474854534238, 'learning_rate': 1.5173785862671653e-05, 'clip_range': 0.13355095227019517, 'gae_lambda': 0.9181855173148512}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'n_steps': IntDistribution(high=8192, log=False, low=2048, step=1), 'gamma': FloatDistribution(high=0.9999, log=True, low=0.8, step=None), 'learning_rate': FloatDistribution(high=0.0001, log=True, low=1e-05, step=None), 'clip_range': FloatDistribution(high=0.4, log=False, low=0.1, step=None), 'gae_lambda': FloatDistribution(high=0.99, log=False, low=0.8, step=None)}, trial_id=0, value=None)

In [70]:
model = PPO.load(os.path.join(OPT_DIR, 'trial_0_best_model.zip'))

FileNotFoundError: [Errno 2] No such file or directory: 'opt/trial_0_best_model.zip.zip'

# Setup Callback

In [72]:
# Import base callback 
from stable_baselines3.common.callbacks import BaseCallback

In [73]:
class TrainAndLoggingCallback(BaseCallback): # continuously learn by starting from best parameters done above

    def __init__(self, check_freq, save_path, verbose=1):
        super(TrainAndLoggingCallback, self).__init__(verbose)
        self.check_freq = check_freq
        self.save_path = save_path

    def _init_callback(self):
        if self.save_path is not None:
            os.makedirs(self.save_path, exist_ok=True)

    def _on_step(self):
        if self.n_calls % self.check_freq == 0:
            model_path = os.path.join(self.save_path, 'best_model_{}'.format(self.n_calls))
            self.model.save(model_path)

        return True

In [74]:
CHECKPOINT_DIR = './train/'

In [75]:
callback = TrainAndLoggingCallback(check_freq=1000, save_path=CHECKPOINT_DIR)

# Train Model

In [76]:
# Create environment 
env = StreetFighter()
env = Monitor(env, LOG_DIR)
env = DummyVecEnv([lambda: env])
env = VecFrameStack(env, 4, channels_order='last')

AssertionError: VecFrameStack only works with gym.spaces.Box and gym.spaces.Dict observation spaces

In [77]:
model_params = study.best_params
model_params['n_steps'] = 7488  # set n_steps to 7488 or a factor of 64
# model_params['learning_rate'] = 5e-7 -> if really slow at training
model_params

ValueError: No trials are completed yet.

In [78]:
model = PPO('CnnPolicy', env, tensorboard_log=LOG_DIR, verbose=1, **model_params) # verbose 1 shows results as training

NameError: name 'model_params' is not defined

In [79]:
# Reload previous weights from HPO
model.load(os.path.join(OPT_DIR, 'trial_0_best_model.zip'))

NameError: name 'model' is not defined

In [80]:
# Kick off training 
model.learn(total_timesteps=5000, callback=callback) # timestep 5000000 recommended

NameError: name 'model' is not defined

In [45]:
# tensorboard --logdir=. 
# cd to logs
# ^ use to visually see learning progress

# Evaluate Model

In [24]:
model = PPO.load('./train/best_model_7000.zip')

d:\StreetFighterRL\env_3\lib\site-packages\stable_baselines3\common\save_util.py:435: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  th_object = th.load(file_content, map_loc

In [25]:
mean_reward, _ = evaluate_policy(model, env, render=True, n_eval_episodes=1)

d:\StreetFighterRL\env_3\lib\site-packages\pyglet\libs\win32\__init__.py:318: UserWarning: Could not set COM MTA mode. Unexpected behavior may occur.
  warnings.warn("Could not set COM MTA mode. Unexpected behavior may occur.")


In [26]:
mean_reward

5900.0

# Testing Model

In [ ]:
obs = env.reset()

In [ ]:
obs.shape

In [ ]:
env.step(model.predict(obs)[0])

In [ ]:
# Reset game to starting state
obs = env.reset()
# Set flag to flase
done = False
for game in range(1): 
    while not done: 
        if done: 
            obs = env.reset()
        env.render()
        action = model.predict(obs)[0]
        obs, reward, done, info = env.step(action)
        time.sleep(0.01)
        print(reward)

## Mucking aboyt.213213231112331

In [72]:
env.close()

In [27]:
env = StreetFighter()
print(env.observation_space)

Box([[[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 ...

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]], [[[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 ...

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]], (84, 84, 1), uint8)


In [ ]:
# pip list

In [ ]:
# was on protobuf 5.28.2

In [ ]:
# please note that pyglet 1.3.2 was for tensorboard, the rendering was for newesrt version